#ifndef CONSTANTS_H__
#define CONSTANTS_H__

// EPD timing constants
#define EPD_REFRESH_TIMEOUT_MS 60000
#define EPD_REFRESH_CHECK_INTERVAL_MS 100
#define EPD_SLEEP_DELAY_MS 200
#define EPD_RESET_PULSE_DURATION_MS 10
#define EPD_BUSY_CHECK_DELAY_MS 1
#define EPD_BUSY_WDT_FEED_INTERVAL 100
#define EPD_SPI_CHUNK_SIZE 200

// EPD write config flags
#define EPD_WRITE_BEGIN_FLAG 0x00
#define EPD_WRITE_CONTINUE_FLAG 0xF0
#define EPD_WRITE_BLACK_FLAG 0x0F
#define EPD_WRITE_COLOR_FLAG 0x00
#define EPD_WRITE_CFG_PLANE1_BEGIN 0x0F
#define EPD_WRITE_CFG_PLANE1_CONTINUE 0xFF
#define EPD_WRITE_CFG_PLANE2_BEGIN 0x00
#define EPD_WRITE_CFG_PLANE2_CONTINUE 0xF0

// Button constants
#define BUTTON_PIN_SETTLE_MS 10
#define BUTTON_PRESS_TIMEOUT_SEC 5
#define BUTTON_MAX_PRESS_COUNT 15
#define BUTTON_ID_MASK 0x07
#define BUTTON_ID_SHIFT 0
#define PRESS_COUNT_MASK 0x0F
#define PRESS_COUNT_SHIFT 3
#define BUTTON_STATE_MASK 0x01
#define BUTTON_STATE_SHIFT 7
#define BUTTON_INVALID_INDEX 0xFF

// LED constants
#define LED_PWM_DELAY_US 100
#define LED_DELAY_FACTOR 100
#define LED_BRIGHTNESS_MASK 0xF0
#define LED_BRIGHTNESS_SHIFT 4
#define LED_MODE_MASK 0x0F
#define LED_INSTANCE_NONE 0xFF
#define LED_FLAG_INVERT_RED 0x01
#define LED_FLAG_INVERT_GREEN 0x02
#define LED_FLAG_INVERT_BLUE 0x04
#define LED_FLAG_INVERT_LED4 0x08

// Config storage constants
#define FDS_WRITE_TIMEOUT_MS 1000
#define FDS_POLL_INTERVAL_MS 10

// System constants
#define WDT_FEED_INTERVAL_SEC 30
#define MSD_UPDATE_INTERVAL_SEC 30

// Config packet IDs
#define CONFIG_PKT_SYSTEM 0x01
#define CONFIG_PKT_MANUFACTURER 0x02
#define CONFIG_PKT_POWER 0x04
#define CONFIG_PKT_DISPLAY 0x20
#define CONFIG_PKT_LED 0x21
#define CONFIG_PKT_SENSOR 0x23
#define CONFIG_PKT_DATA_BUS 0x24
#define CONFIG_PKT_BINARY_INPUT 0x25
#define CONFIG_PKT_WIFI 0x26

// GPIO pin constants
#define GPIO_PIN_UNUSED 0xFF

#endif // CONSTANTS_H__
